"""create bars table

Revision ID: 1bfd60094c50
Revises: 
Create Date: 2026-10-01 14:59:33.899292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bfd60094c50'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bars',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('close BETWEEN low AND high', name=op.f('ck_bars_close_in_range')),
    sa.CheckConstraint('high >= low', name=op.f('ck_bars_high_gte_low')),
    sa.CheckConstraint('low > 0', name=op.f('ck_bars_low_positive')),
    sa.CheckConstraint('open BETWEEN low AND high', name=op.f('ck_bars_open_in_range')),
    sa.CheckConstraint('volume >= 0', name=op.f('ck_bars_volume_non_negative')),
    sa.PrimaryKeyConstraint('symbol', 'timeframe', 'ts', name=op.f('pk_bars'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bars')
    # ### end Alembic commands ###
