/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bars */
        get: operations["list_bars_api_v1_bars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Symbols */
        get: operations["list_symbols_api_v1_symbols_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Backtest */
        post: operations["create_backtest_api_v1_backtests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BacktestRequest */
        "BacktestRequest-Input": {
            /** Symbols */
            symbols: string[];
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /**
             * Fast
             * @default 10
             */
            fast: number;
            /**
             * Slow
             * @default 30
             */
            slow: number;
            /**
             * Capital
             * @default 100000
             */
            capital: number | string;
            /**
             * Cash Rate
             * @default 0.02
             */
            cash_rate: number | string;
            /**
             * Benchmark
             * @default SPY
             */
            benchmark: string;
        };
        /** BacktestRequest */
        "BacktestRequest-Output": {
            /** Symbols */
            symbols: string[];
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /**
             * Fast
             * @default 10
             */
            fast: number;
            /**
             * Slow
             * @default 30
             */
            slow: number;
            /**
             * Capital
             * @default 100000
             */
            capital: string;
            /**
             * Cash Rate
             * @default 0.02
             */
            cash_rate: string;
            /**
             * Benchmark
             * @default SPY
             */
            benchmark: string;
        };
        /** BacktestResponse */
        BacktestResponse: {
            /** Run Id */
            run_id: string;
            params: components["schemas"]["BacktestRequest-Output"];
            /** Trading Days */
            trading_days: number;
            /** Starting Value */
            starting_value: string;
            strategy: components["schemas"]["CurveMetrics"];
            benchmark: components["schemas"]["CurveMetrics"] | null;
            relative: components["schemas"]["RelativeMetrics"];
            trade_summary: components["schemas"]["TradeSummary"];
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Open Positions */
            open_positions: {
                [key: string]: number;
            };
            /** Equity Curve */
            equity_curve: components["schemas"]["EquityPoint"][];
            /** Trades */
            trades: components["schemas"]["TradeOut"][];
        };
        /** BarOut */
        BarOut: {
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Open */
            open: string;
            /** High */
            high: string;
            /** Low */
            low: string;
            /** Close */
            close: string;
            /** Volume */
            volume: string;
            /** Source */
            source: string;
        };
        /** CurveMetrics */
        CurveMetrics: {
            /** Total Return */
            total_return: number;
            /** Cagr */
            cagr: number | null;
            /** Volatility */
            volatility: number | null;
            /** Sharpe */
            sharpe: number | null;
            /** Sortino */
            sortino: number | null;
            /** Calmar */
            calmar: number | null;
            /** Max Drawdown */
            max_drawdown: number;
            /** Drawdown Peak */
            drawdown_peak: string | null;
            /** Drawdown Trough */
            drawdown_trough: string | null;
            /** Drawdown Recovered */
            drawdown_recovered: string | null;
            /** Drawdown Days */
            drawdown_days: number;
        };
        /** EquityPoint */
        EquityPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Equity */
            equity: string;
            /** Benchmark */
            benchmark: string | null;
            /** Exposure */
            exposure: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Status */
            status: string;
            /** Database */
            database: string;
        };
        /** RelativeMetrics */
        RelativeMetrics: {
            /** Beta */
            beta: number | null;
            /** Correlation */
            correlation: number | null;
            /** Alpha */
            alpha: number | null;
        };
        /** SymbolInfo */
        SymbolInfo: {
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
            /** Bars */
            bars: number;
            /**
             * First
             * Format: date-time
             */
            first: string;
            /**
             * Last
             * Format: date-time
             */
            last: string;
        };
        /**
         * Timeframe
         * @enum {string}
         */
        Timeframe: "1Min" | "5Min" | "15Min" | "1Hour" | "1Day";
        /** TradeOut */
        TradeOut: {
            /** Symbol */
            symbol: string;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /**
             * Closed At
             * Format: date-time
             */
            closed_at: string;
            /** Quantity */
            quantity: number;
            /** Avg Entry */
            avg_entry: string;
            /** Avg Exit */
            avg_exit: string;
            /** Net Pnl */
            net_pnl: string;
            /** Exit Reason */
            exit_reason: string;
        };
        /** TradeSummary */
        TradeSummary: {
            /** Count */
            count: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Win Rate */
            win_rate: number | null;
            /** Avg Win */
            avg_win: number | null;
            /** Avg Loss */
            avg_loss: number | null;
            /** Payoff Ratio */
            payoff_ratio: number | null;
            /** Profit Factor */
            profit_factor: number | null;
            /** Expectancy */
            expectancy: number | null;
            /** Avg Holding Days */
            avg_holding_days: number | null;
            /** Best Trade Share */
            best_trade_share: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    list_bars_api_v1_bars_get: {
        parameters: {
            query: {
                symbol: string;
                timeframe: components["schemas"]["Timeframe"];
                start: string;
                end: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_symbols_api_v1_symbols_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolInfo"][];
                };
            };
        };
    };
    create_backtest_api_v1_backtests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRequest-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
